"""Tune the cost scheduler's weights on one benchmark workload, validated on held-out seeds.

Usage (from the project root):
    python simulation/tune_cost_weights.py                      # workload C, 30 candidates
    python simulation/tune_cost_weights.py --workload B --candidates 50

Writes the best weights to configs/scheduling_tuned.yaml (the default configs/scheduling.yaml is never
overwritten) and a report to results/reports/tuning_report.md.
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from dataclasses import fields
from pathlib import Path

from bioflow.analytics.performance import load_benchmark_plan
from bioflow.analytics.tuning import Evaluation, TuningResult, tune, weights_yaml
from bioflow.core.exceptions import BioFlowError
from bioflow.scheduling.config import CostSettings, CostWeights, load_scheduling_config


def _weights(e: Evaluation) -> str:
    return ", ".join(f"{f.name}={getattr(e.weights, f.name):g}" for f in fields(CostWeights))


def report(result: TuningResult, workload: str, train: list[int], test: list[int], elapsed: float) -> str:
    verdict = (
        "The tuned weights **also beat the defaults on the held-out seeds**, so the improvement generalises "
        "to unseen workloads of this kind."
        if result.generalises else
        "The tuned weights did **not** beat the defaults on the held-out seeds: the training improvement did "
        "not generalise, so the defaults are kept."
    )
    top = sorted(result.candidates, key=lambda e: e.objective)[:5]
    lines = [
        "# Cost-scheduler weight tuning", "",
        f"Workload **{workload}**; {len(result.candidates)} candidates (including the current defaults); "
        f"training seeds {train}, held-out test seeds {test}; {elapsed:.0f} s.", "",
        "Objective per seed = fraction of experiments late + (makespan / FIFO makespan - 1). "
        "Lower is better. FIFO scores exactly its own late fraction.", "",
        "| Weights | Training objective | Held-out objective |", "|---|---|---|",
        f"| current defaults | {result.default.objective:.3f} | {result.test_default.objective:.3f} |",
        f"| best on training | {result.best.objective:.3f} | {result.test_best.objective:.3f} |",
        f"| FIFO (reference) | - | {result.test_fifo_objective:.3f} |", "",
        verdict, "",
        f"Best weights: `{_weights(result.best)}`", "",
        "## Top five candidates on the training seeds", "", "| Objective | Weights |", "|---|---|",
        *[f"| {e.objective:.3f} | `{_weights(e)}` |" for e in top], "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Tune the cost scheduler's weights.")
    parser.add_argument("--config", type=Path, default=Path("configs/benchmarks.yaml"))
    parser.add_argument("--workload", default="C")
    parser.add_argument("--candidates", type=int, default=30)
    parser.add_argument("--train-seeds", type=int, nargs="+", default=[101, 102, 103])
    parser.add_argument("--test-seeds", type=int, nargs="+", default=[201, 202, 203, 204, 205])
    parser.add_argument("--out", type=Path, default=Path("configs/scheduling_tuned.yaml"))
    args = parser.parse_args(argv)
    logging.getLogger("bioflow").setLevel(logging.ERROR)
    overlap = set(args.train_seeds) & set(args.test_seeds)
    if overlap:
        parser.error(f"training and test seeds must not overlap: {sorted(overlap)}")

    try:
        plan = load_benchmark_plan(args.config)
        spec = plan.workloads[args.workload]
        base = load_scheduling_config(spec.scheduling_config).cost if spec.scheduling_config else CostSettings()
        started = time.perf_counter()

        def progress(index: int, evaluation: Evaluation) -> None:
            tag = "defaults" if index == 0 else f"candidate {index:>3}"
            print(f"{tag:<14} objective {evaluation.objective:7.3f}   {_weights(evaluation)}", flush=True)

        result = tune(spec, args.train_seeds, args.test_seeds, args.candidates, base=base, progress=progress)
        elapsed = time.perf_counter() - started
    except (BioFlowError, KeyError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    note = (f"Tuned on workload {args.workload}, training seeds {args.train_seeds}; held-out objective "
            f"{result.test_best.objective:.3f} vs defaults {result.test_default.objective:.3f}. "
            "Generated by simulation/tune_cost_weights.py.")
    args.out.write_text(weights_yaml(result.best.weights, base, note), encoding="utf-8")
    report_path = Path("results/reports/tuning_report.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report(result, args.workload, args.train_seeds, args.test_seeds, elapsed),
                           encoding="utf-8")
    print(f"\nHeld-out objective: defaults {result.test_default.objective:.3f}, tuned {result.test_best.objective:.3f}"
          f" -> {'generalises' if result.generalises else 'does not generalise'}")
    print(f"Weights: {args.out}   Report: {report_path}   ({elapsed:.0f} s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
